import { ROCKET_SVG, FIRE_HEART_SVG, FIRE_SVG, CLAP_SVG, NEUTRAL_FACE_SVG, POOP_SVG, CLOWN_SVG, MAD_FACE_SVG, CRY_FACE_SVG } from "./svgs";

export const DEFAULT_SCORE_SVG_MAP: { [key: number]: string } = {
  0: ROCKET_SVG,
  1: FIRE_HEART_SVG,
  2: FIRE_SVG,
  3: CLAP_SVG,
  4: NEUTRAL_FACE_SVG,
  5: MAD_FACE_SVG,
  6: CRY_FACE_SVG,
  7: POOP_SVG,
  8: CLOWN_SVG,
}